import type {
  Candidate,
  JobReq,
  Assessment,
  Recruiter,
  Activity,
  PipelineStage,
  Analytics,
} from "./types";

export const demoRecruiters: Recruiter[] = [
  {
    id: "rec_jenna",
    fullName: "Jenna Park",
    email: "jenna@techhire.example.test",
    role: "Senior Technical Recruiter",
    activeReqs: 4,
    candidatesInPipeline: 27,
    hiresThisQuarter: 3,
    timeToFillAvg: 34,
  },
  {
    id: "rec_derek",
    fullName: "Derek Okonkwo",
    email: "derek@techhire.example.test",
    role: "Technical Recruiter",
    activeReqs: 3,
    candidatesInPipeline: 19,
    hiresThisQuarter: 2,
    timeToFillAvg: 41,
  },
  {
    id: "rec_sanya",
    fullName: "Sanya Gupta",
    email: "sanya@techhire.example.test",
    role: "Sourcing Lead",
    activeReqs: 5,
    candidatesInPipeline: 34,
    hiresThisQuarter: 1,
    timeToFillAvg: 47,
  },
];

export const demoJobReqs: JobReq[] = [
  {
    id: "req_sr_backend",
    title: "Senior Backend Engineer (Java/Kotlin)",
    department: "Platform Engineering",
    seniority: "senior",
    location: "San Francisco, CA (Hybrid)",
    requiredSkills: ["Java", "Kotlin", "Spring Boot", "PostgreSQL", "Kafka"],
    targetSalaryMin: 185000,
    targetSalaryMax: 240000,
    candidatesNeeded: 2,
    hiredCount: 0,
    openedAt: "2026-04-01T08:00:00Z",
    targetFillDate: "2026-07-01T00:00:00Z",
    status: "open",
    priority: "high",
  },
  {
    id: "req_staff_platform",
    title: "Staff Platform Engineer (Kotlin)",
    department: "Infrastructure",
    seniority: "staff",
    location: "Remote (US)",
    requiredSkills: ["Kotlin", "gRPC", "Kubernetes", "AWS", "Terraform"],
    targetSalaryMin: 230000,
    targetSalaryMax: 290000,
    candidatesNeeded: 1,
    hiredCount: 0,
    openedAt: "2026-03-15T08:00:00Z",
    targetFillDate: "2026-06-15T00:00:00Z",
    status: "open",
    priority: "high",
  },
  {
    id: "req_mid_services",
    title: "Mid-Level Backend Services Developer (Java)",
    department: "Payments",
    seniority: "mid",
    location: "Austin, TX",
    requiredSkills: ["Java", "Spring Boot", "MySQL", "Redis", "Docker"],
    targetSalaryMin: 130000,
    targetSalaryMax: 165000,
    candidatesNeeded: 3,
    hiredCount: 1,
    openedAt: "2026-02-01T08:00:00Z",
    targetFillDate: "2026-05-01T00:00:00Z",
    status: "open",
    priority: "medium",
  },
];

export const demoCandidates: Candidate[] = [
  {
    id: "cand_001",
    fullName: "Marco Rivera",
    currentRole: "Senior Backend Engineer",
    currentCompany: "Finova Payments",
    yearsExperience: 8,
    seniority: "senior",
    location: "San Francisco, CA",
    skills: ["Java", "Kotlin", "Spring Boot", "PostgreSQL", "Kafka", "Docker"],
    status: "team_interview",
    jobReqId: "req_sr_backend",
    source: "linkedin",
    aiMatchScore: 94,
    expectedSalary: 225000,
    recruiterId: "rec_jenna",
    appliedAt: "2026-04-10T14:30:00Z",
    lastContactAt: "2026-06-09T09:15:00Z",
    notes: "Strong experience with event-driven architectures. Previously at Stripe.",
    integrity: {
      identityStatus: "verified",
      workHistoryStatus: "verified",
      liveInterviewStatus: "verified",
      fraudRisk: "low",
      reviewOwner: null,
      nextReviewAt: null,
      evidence: [
        "ID rechecked before live team interview",
        "Work history matched Stripe reference and LinkedIn employment dates",
        "Live concurrency follow-up matched take-home implementation choices",
      ],
    },
  },
  {
    id: "cand_002",
    fullName: "Aisha Okafor",
    currentRole: "Backend Engineer II",
    currentCompany: "Databridge Inc",
    yearsExperience: 5,
    seniority: "mid",
    location: "Austin, TX",
    skills: ["Java", "Spring Boot", "MySQL", "Redis", "Docker"],
    status: "offer",
    jobReqId: "req_mid_services",
    source: "referral",
    aiMatchScore: 88,
    expectedSalary: 155000,
    recruiterId: "rec_derek",
    appliedAt: "2026-02-20T11:00:00Z",
    lastContactAt: "2026-06-08T16:45:00Z",
    notes: "Referred by current team member. Strong culture fit.",
    integrity: {
      identityStatus: "verified",
      workHistoryStatus: "verified",
      liveInterviewStatus: "verified",
      fraudRisk: "low",
      reviewOwner: null,
      nextReviewAt: null,
      evidence: [
        "Referral source confirmed current team-member relationship",
        "Employment dates verified against Databridge reference",
        "Offer-stage live panel confirmed candidate matched phone-screen notes",
      ],
    },
  },
  {
    id: "cand_003",
    fullName: "Viktor Sokolov",
    currentRole: "Staff Software Engineer",
    currentCompany: "CloudScale Systems",
    yearsExperience: 12,
    seniority: "staff",
    location: "Seattle, WA",
    skills: ["Kotlin", "gRPC", "Kubernetes", "AWS", "Terraform", "Go"],
    status: "coding_assessment",
    jobReqId: "req_staff_platform",
    source: "github",
    aiMatchScore: 96,
    expectedSalary: 275000,
    recruiterId: "rec_jenna",
    appliedAt: "2026-04-05T10:00:00Z",
    lastContactAt: "2026-06-07T14:00:00Z",
    notes: "Kotlin OSS contributor. Built gRPC framework used at AWS.",
    integrity: {
      identityStatus: "verified",
      workHistoryStatus: "needs_follow_up",
      liveInterviewStatus: "not_started",
      fraudRisk: "medium",
      reviewOwner: "Jenna Park",
      nextReviewAt: "2026-06-12T17:00:00Z",
      evidence: [
        "GitHub maintainer identity matched long-running Kotlin commit history",
        "CloudScale employment verification is pending recruiter follow-up",
        "Camera-on coding session scheduled to rule out proxy interview risk",
      ],
    },
  },
  {
    id: "cand_004",
    fullName: "Leila Hosseini",
    currentRole: "Senior Java Developer",
    currentCompany: "TradeFlow Capital",
    yearsExperience: 9,
    seniority: "senior",
    location: "San Jose, CA",
    skills: ["Java", "Kotlin", "Spring Boot", "Kafka", "PostgreSQL"],
    status: "screening",
    jobReqId: "req_sr_backend",
    source: "agency",
    aiMatchScore: 82,
    expectedSalary: 210000,
    recruiterId: "rec_sanya",
    appliedAt: "2026-05-22T09:00:00Z",
    lastContactAt: "2026-06-04T11:30:00Z",
    notes: "Capital markets background. Strong concurrent systems knowledge.",
    integrity: {
      identityStatus: "needs_follow_up",
      workHistoryStatus: "verified",
      liveInterviewStatus: "not_started",
      fraudRisk: "medium",
      reviewOwner: "Sanya Gupta",
      nextReviewAt: "2026-06-11T18:00:00Z",
      evidence: [
        "Agency submission requires direct ID verification before technical panel",
        "TradeFlow work history verified through agency reference packet",
        "Phone-screen notes include follow-up to compare live debugging style",
      ],
    },
  },
  {
    id: "cand_005",
    fullName: "James Chen",
    currentRole: "Backend Engineer",
    currentCompany: "QuickShip Logistics",
    yearsExperience: 4,
    seniority: "mid",
    location: "Austin, TX",
    skills: ["Java", "Spring Boot", "MySQL", "Docker", "Kubernetes"],
    status: "hired",
    jobReqId: "req_mid_services",
    source: "linkedin",
    aiMatchScore: 85,
    expectedSalary: 145000,
    recruiterId: "rec_derek",
    appliedAt: "2026-02-14T08:00:00Z",
    lastContactAt: "2026-05-20T10:00:00Z",
    notes: "Started June 2. Ramping up on payments domain.",
    integrity: {
      identityStatus: "verified",
      workHistoryStatus: "verified",
      liveInterviewStatus: "verified",
      fraudRisk: "low",
      reviewOwner: null,
      nextReviewAt: null,
      evidence: [
        "Onboarding identity check completed before start date",
        "QuickShip reference confirmed logistics platform ownership",
        "Live payments-domain interview matched take-home API decisions",
      ],
    },
  },
  {
    id: "cand_006",
    fullName: "Priya Natarajan",
    currentRole: "Platform Engineer",
    currentCompany: "NetScale",
    yearsExperience: 7,
    seniority: "senior",
    location: "New York, NY",
    skills: ["Kotlin", "Java", "Kubernetes", "AWS", "Terraform"],
    status: "system_design",
    jobReqId: "req_staff_platform",
    source: "referral",
    aiMatchScore: 79,
    expectedSalary: 250000,
    recruiterId: "rec_jenna",
    appliedAt: "2026-05-01T13:00:00Z",
    lastContactAt: "2026-06-06T15:30:00Z",
    notes: "Strong infra background but less Kotlin depth. Consider for senior instead of staff.",
    integrity: {
      identityStatus: "verified",
      workHistoryStatus: "verified",
      liveInterviewStatus: "verified",
      fraudRisk: "low",
      reviewOwner: null,
      nextReviewAt: null,
      evidence: [
        "Referral chain verified through current NetScale engineering contact",
        "Work history confirmed for Kubernetes and AWS platform ownership",
        "System-design panel included unscripted trade-off questions",
      ],
    },
  },
  {
    id: "cand_007",
    fullName: "Thomas Berger",
    currentRole: "Lead Backend Engineer",
    currentCompany: "AutoDesk Germany",
    yearsExperience: 10,
    seniority: "senior",
    location: "Remote (Germany)",
    skills: ["Java", "Kotlin", "Spring Boot", "PostgreSQL", "Kafka"],
    status: "declined",
    jobReqId: "req_sr_backend",
    source: "stack_overflow",
    aiMatchScore: 91,
    expectedSalary: 195000,
    recruiterId: "rec_jenna",
    appliedAt: "2026-04-18T07:00:00Z",
    lastContactAt: "2026-05-15T12:00:00Z",
    notes: "Declined. Visa timeline too long; accepted local offer in Berlin.",
    integrity: {
      identityStatus: "verified",
      workHistoryStatus: "verified",
      liveInterviewStatus: "verified",
      fraudRisk: "low",
      reviewOwner: null,
      nextReviewAt: null,
      evidence: [
        "Stack Overflow profile matched verified email and public contributions",
        "Employment history aligned with Germany-based engineering references",
        "Live visa-timeline conversation matched prior recruiter notes",
      ],
    },
  },
  {
    id: "cand_008",
    fullName: "Cynthia Mwangi",
    currentRole: "Software Engineer III",
    currentCompany: "HealthTech Africa",
    yearsExperience: 6,
    seniority: "mid",
    location: "Austin, TX",
    skills: ["Java", "Spring Boot", "MySQL", "Docker", "GraphQL"],
    status: "coding_assessment",
    jobReqId: "req_mid_services",
    source: "inbound",
    aiMatchScore: 83,
    expectedSalary: 140000,
    recruiterId: "rec_derek",
    appliedAt: "2026-05-10T16:00:00Z",
    lastContactAt: "2026-06-03T09:00:00Z",
    notes: "Completed take-home. Scheduling live coding round.",
    integrity: {
      identityStatus: "verified",
      workHistoryStatus: "verified",
      liveInterviewStatus: "not_started",
      fraudRisk: "low",
      reviewOwner: "Derek Okonkwo",
      nextReviewAt: "2026-06-12T15:00:00Z",
      evidence: [
        "Inbound application identity verified before take-home review",
        "HealthTech Africa reference confirmed API and GraphQL ownership",
        "Live coding session scheduled to validate take-home authorship",
      ],
    },
  },
  {
    id: "cand_009",
    fullName: "Rafael Torres",
    currentRole: "Distinguished Engineer",
    currentCompany: "Oracle",
    yearsExperience: 15,
    seniority: "principal",
    location: "Redwood City, CA",
    skills: ["Java", "Kotlin", "Spring", "PostgreSQL", "Kafka", "gRPC", "Kubernetes"],
    status: "sourced",
    jobReqId: "req_staff_platform",
    source: "linkedin",
    aiMatchScore: 98,
    expectedSalary: 310000,
    recruiterId: "rec_sanya",
    appliedAt: "2026-06-01T10:00:00Z",
    lastContactAt: "2026-06-05T13:00:00Z",
    notes: "Overqualified on paper but open to IC staff role. Reach out for exploratory.",
    integrity: {
      identityStatus: "needs_follow_up",
      workHistoryStatus: "verified",
      liveInterviewStatus: "not_started",
      fraudRisk: "medium",
      reviewOwner: "Sanya Gupta",
      nextReviewAt: "2026-06-13T17:00:00Z",
      evidence: [
        "Principal-level outreach needs identity follow-up before exploratory screen",
        "Oracle employment signals match public conference and patent history",
        "Recruiter flagged salary and level mismatch for live conversation",
      ],
    },
  },
  {
    id: "cand_010",
    fullName: "Anna Lindqvist",
    currentRole: "Senior Backend Developer",
    currentCompany: "Spotify",
    yearsExperience: 8,
    seniority: "senior",
    location: "Remote (Sweden)",
    skills: ["Java", "Kotlin", "gRPC", "PostgreSQL", "Kafka", "AWS"],
    status: "offer",
    jobReqId: "req_sr_backend",
    source: "github",
    aiMatchScore: 92,
    expectedSalary: 235000,
    recruiterId: "rec_jenna",
    appliedAt: "2026-04-25T08:00:00Z",
    lastContactAt: "2026-06-10T10:00:00Z",
    notes: "Offer extended June 9. Expecting response by June 13.",
    integrity: {
      identityStatus: "verified",
      workHistoryStatus: "verified",
      liveInterviewStatus: "verified",
      fraudRisk: "low",
      reviewOwner: null,
      nextReviewAt: null,
      evidence: [
        "GitHub identity matched Spotify email-domain contribution history",
        "Work history verified during offer-stage reference check",
        "Live system-design panel confirmed unaided distributed-systems reasoning",
      ],
    },
  },
  {
    id: "cand_011",
    fullName: "Diego Herrera",
    currentRole: "Backend Developer",
    currentCompany: "StartupX",
    yearsExperience: 3,
    seniority: "junior",
    location: "Austin, TX",
    skills: ["Java", "Spring Boot", "MySQL", "Docker"],
    status: "screening",
    jobReqId: "req_mid_services",
    source: "agency",
    aiMatchScore: 62,
    expectedSalary: 120000,
    recruiterId: "rec_sanya",
    appliedAt: "2026-05-28T14:00:00Z",
    lastContactAt: "2026-06-02T11:00:00Z",
    notes: "Low experience but strong project portfolio. Consider junior track.",
    integrity: {
      identityStatus: "needs_follow_up",
      workHistoryStatus: "needs_follow_up",
      liveInterviewStatus: "not_started",
      fraudRisk: "medium",
      reviewOwner: "Sanya Gupta",
      nextReviewAt: "2026-06-11T16:00:00Z",
      evidence: [
        "Agency profile has junior-to-mid title mismatch requiring recruiter follow-up",
        "StartupX work history awaits direct reference verification",
        "Portfolio review will include live walkthrough to reduce proxy-work risk",
      ],
    },
  },
  {
    id: "cand_012",
    fullName: "Yuki Tanaka",
    currentRole: "Senior Software Engineer",
    currentCompany: "Rakuten",
    yearsExperience: 9,
    seniority: "senior",
    location: "San Francisco, CA",
    skills: ["Java", "Kotlin", "Spring Boot", "MySQL", "Kafka", "Docker"],
    status: "withdrawn",
    jobReqId: "req_sr_backend",
    source: "linkedin",
    aiMatchScore: 87,
    expectedSalary: 220000,
    recruiterId: "rec_jenna",
    appliedAt: "2026-04-12T09:00:00Z",
    lastContactAt: "2026-05-20T16:00:00Z",
    notes: "Withdrew after accepting counter-offer from current employer.",
    integrity: {
      identityStatus: "verified",
      workHistoryStatus: "verified",
      liveInterviewStatus: "verified",
      fraudRisk: "low",
      reviewOwner: null,
      nextReviewAt: null,
      evidence: [
        "LinkedIn identity matched Rakuten engineering network",
        "Work history verified before candidate withdrew",
        "Live screen matched resume claims before counter-offer withdrawal",
      ],
    },
  },
  {
    id: "cand_013",
    fullName: "Marcus Whitfield",
    currentRole: "Platform Engineer II",
    currentCompany: "Tesla",
    yearsExperience: 6,
    seniority: "mid",
    location: "Austin, TX",
    skills: ["Java", "Kotlin", "Kubernetes", "AWS", "Terraform"],
    status: "team_interview",
    jobReqId: "req_mid_services",
    source: "conference",
    aiMatchScore: 81,
    expectedSalary: 158000,
    recruiterId: "rec_derek",
    appliedAt: "2026-05-05T12:00:00Z",
    lastContactAt: "2026-06-09T08:30:00Z",
    notes: "Met at KubeCon. Strong infra side; needs payments domain ramp.",
    integrity: {
      identityStatus: "verified",
      workHistoryStatus: "verified",
      liveInterviewStatus: "verified",
      fraudRisk: "low",
      reviewOwner: null,
      nextReviewAt: null,
      evidence: [
        "Conference source verified candidate identity at KubeCon follow-up",
        "Tesla platform work validated through domain-specific live questions",
        "Team interview scheduled because live debug exposed real concurrency gaps",
      ],
    },
  },
];

export const demoAssessments: Assessment[] = [
  {
    id: "asmt_001",
    candidateId: "cand_001",
    type: "coding",
    result: "pass",
    score: 88,
    maxScore: 100,
    grader: "Engineering Team",
    humanReviewedAt: "2026-05-20T17:00:00Z",
    calibrationNotes: "Peer review confirmed concurrency solution met rubric; minor style feedback kept score below 90.",
    aiAssistancePolicy: "company_sandbox",
    aiUsageEvidence: [
      "Prompt log disclosed use of the approved coding sandbox for test scaffolding",
      "Live follow-up showed the candidate correcting an AI-suggested locking bug",
    ],
    aiFluencyReview: "Used the sandbox to accelerate tests, then caught a race condition and explained the backpressure trade-off clearly.",
    completedAt: "2026-05-20T14:00:00Z",
    notes: "Clean code, strong concurrency handling. Minor style nits.",
  },
  {
    id: "asmt_002",
    candidateId: "cand_001",
    type: "system_design",
    result: "pass",
    score: 91,
    maxScore: 100,
    grader: "Platform Lead",
    humanReviewedAt: "2026-06-02T13:30:00Z",
    calibrationNotes: "Platform lead confirmed the design covered backpressure, failure modes, and event boundaries.",
    aiAssistancePolicy: "not_allowed",
    aiUsageEvidence: ["Whiteboard-only design panel; no assistant tools were permitted"],
    aiFluencyReview: "Panel assessed unaided architecture judgment, with emphasis on trade-offs and failure-mode explanation.",
    completedAt: "2026-06-02T10:00:00Z",
    notes: "Excellent event-driven design. Handled failure modes well.",
  },
  {
    id: "asmt_003",
    candidateId: "cand_003",
    type: "coding",
    result: "pending",
    score: 0,
    maxScore: 100,
    grader: "Engineering Team",
    humanReviewedAt: null,
    calibrationNotes: "Queued for senior engineer calibration once the Kotlin + gRPC assessment is completed.",
    aiAssistancePolicy: "unknown",
    aiUsageEvidence: [],
    aiFluencyReview: "Pending assessment; reviewer will capture approved tool use, prompt logs, and live-debug evidence after completion.",
    completedAt: "2026-06-10T08:00:00Z",
    notes: "Scheduled for June 12. Kotlin + gRPC focus.",
  },
  {
    id: "asmt_004",
    candidateId: "cand_008",
    type: "take_home",
    result: "pass",
    score: 82,
    maxScore: 100,
    grader: "Hiring Manager",
    humanReviewedAt: "2026-05-29T09:15:00Z",
    calibrationNotes: "Hiring manager reviewed SQL concerns; pass held below top band until optimization follow-up.",
    aiAssistancePolicy: "allowed_with_disclosure",
    aiUsageEvidence: [
      "Candidate disclosed Copilot-assisted repository setup in the take-home README",
      "SQL tuning follow-up required the candidate to explain query-plan changes without prompts",
    ],
    aiFluencyReview: "Disclosed assistant use, separated generated boilerplate from original API design, and explained the SQL optimization trade-offs.",
    completedAt: "2026-05-28T17:00:00Z",
    notes: "Good API design. SQL queries could use optimization.",
  },
  {
    id: "asmt_005",
    candidateId: "cand_010",
    type: "coding",
    result: "pass",
    score: 94,
    maxScore: 100,
    grader: "Engineering Team",
    humanReviewedAt: "2026-05-15T16:30:00Z",
    calibrationNotes: "Second engineer confirmed tests and idiomatic Kotlin justify a top-band pass.",
    aiAssistancePolicy: "company_sandbox",
    aiUsageEvidence: [
      "Approved sandbox transcript shows the candidate iterating on edge-case tests",
      "Reviewer observed candidate rejecting an incorrect AI suggestion for coroutine cancellation",
    ],
    aiFluencyReview: "Used AI as a pair-programming aid while preserving ownership of tests, correctness checks, and Kotlin concurrency decisions.",
    completedAt: "2026-05-15T12:00:00Z",
    notes: "Exceptional. Idiomatic Kotlin, thorough tests.",
  },
  {
    id: "asmt_006",
    candidateId: "cand_010",
    type: "system_design",
    result: "pass",
    score: 90,
    maxScore: 100,
    grader: "Platform Lead",
    humanReviewedAt: "2026-05-28T18:00:00Z",
    calibrationNotes: "Architecture panel confirmed distributed-systems tradeoffs met the senior backend bar.",
    aiAssistancePolicy: "not_allowed",
    aiUsageEvidence: ["Live system-design panel; no external assistant tools were allowed"],
    aiFluencyReview: "Panel focused on unaided reasoning about distributed-system trade-offs and communication clarity.",
    completedAt: "2026-05-28T15:00:00Z",
    notes: "Strong distributed systems knowledge. Clear communication.",
  },
  {
    id: "asmt_007",
    candidateId: "cand_013",
    type: "coding",
    result: "marginal",
    score: 68,
    maxScore: 100,
    grader: "Engineering Team",
    humanReviewedAt: "2026-05-26T14:45:00Z",
    calibrationNotes: "Human review kept the marginal label because concurrency gaps need live follow-up despite solid Kotlin.",
    aiAssistancePolicy: "allowed_with_disclosure",
    aiUsageEvidence: [
      "Candidate disclosed ChatGPT use for concurrent-map examples",
      "Live debug follow-up exposed gaps in explaining stale reads and lock contention",
    ],
    aiFluencyReview: "Disclosed AI help but could not fully debug the generated concurrency pattern, so the score stayed marginal.",
    completedAt: "2026-05-26T11:00:00Z",
    notes: "Solid Kotlin but struggled with concurrent data structures.",
  },
  {
    id: "asmt_008",
    candidateId: "cand_006",
    type: "system_design",
    result: "pass",
    score: 85,
    maxScore: 100,
    grader: "Platform Lead",
    humanReviewedAt: "2026-06-04T18:20:00Z",
    calibrationNotes: "Platform lead calibrated this as pass while preserving an application-layer follow-up for staff fit.",
    aiAssistancePolicy: "not_allowed",
    aiUsageEvidence: ["System-design panel used interviewer-provided prompts only"],
    aiFluencyReview: "Assessed unaided architecture reasoning; application-layer follow-up remains the next evidence point.",
    completedAt: "2026-06-04T16:00:00Z",
    notes: "Good infra design. Weaker on application-layer patterns.",
  },
];

export const demoActivities: Activity[] = [
  {
    id: "act_001",
    candidateId: "cand_010",
    type: "offer_sent",
    timestamp: "2026-06-09T14:30:00Z",
    summary: "Offer letter sent: Senior Backend Engineer, $235K base + equity. Candidate has until June 13 to respond.",
    outcome: "positive",
  },
  {
    id: "act_002",
    candidateId: "cand_001",
    type: "interview_scheduled",
    timestamp: "2026-06-09T09:00:00Z",
    summary: "Team interview confirmed for June 11 with 4 engineers from Platform team.",
    outcome: "neutral",
  },
  {
    id: "act_003",
    candidateId: "cand_003",
    type: "assessment_graded",
    timestamp: "2026-06-08T16:00:00Z",
    summary: "Initial phone screen passed. Coding assessment scheduled for June 12.",
    outcome: "positive",
  },
  {
    id: "act_004",
    candidateId: "cand_008",
    type: "assessment_graded",
    timestamp: "2026-06-03T10:00:00Z",
    summary: "Take-home assessment reviewed: 82/100. Proceeding to live coding round.",
    outcome: "positive",
  },
  {
    id: "act_005",
    candidateId: "cand_006",
    type: "feedback_received",
    timestamp: "2026-06-06T14:00:00Z",
    summary: "System design panel feedback: strong on infra, recommend team interview. Flag: not quite staff-level architecture depth.",
    outcome: "neutral",
  },
  {
    id: "act_006",
    candidateId: "cand_004",
    type: "note_added",
    timestamp: "2026-06-04T11:30:00Z",
    summary: "Phone screen completed. Candidate has capital markets domain knowledge relevant to trading platform work.",
    outcome: "positive",
  },
  {
    id: "act_007",
    candidateId: "cand_009",
    type: "message_sent",
    timestamp: "2026-06-05T13:00:00Z",
    summary: "LinkedIn InMail sent to Rafael Torres. Highlighted staff-level IC role with no management responsibilities.",
    outcome: "neutral",
  },
  {
    id: "act_008",
    candidateId: "cand_013",
    type: "status_change",
    timestamp: "2026-06-09T08:30:00Z",
    summary: "Advanced to team interview stage after marginal coding result. Hiring manager wants to evaluate communication skills.",
    outcome: "neutral",
  },
  {
    id: "act_009",
    candidateId: "cand_002",
    type: "message_sent",
    timestamp: "2026-06-08T16:45:00Z",
    summary: "Sent offer package details. Candidate is reviewing and will respond within 48 hours.",
    outcome: "positive",
  },
  {
    id: "act_010",
    candidateId: "cand_005",
    type: "status_change",
    timestamp: "2026-06-02T09:00:00Z",
    summary: "Started onboarding! First day in Payments team. Assigned mentor and initial sprint tasks.",
    outcome: "positive",
  },
];

export const demoPipelineStages: PipelineStage[] = [
  { id: "stage_source", name: "Sourced", order: 1, candidateCount: 14, passRate: 100 },
  { id: "stage_screen", name: "Screening", order: 2, candidateCount: 11, passRate: 79 },
  { id: "stage_coding", name: "Coding Assessment", order: 3, candidateCount: 8, passRate: 72 },
  { id: "stage_design", name: "System Design", order: 4, candidateCount: 5, passRate: 63 },
  { id: "stage_team", name: "Team Interview", order: 5, candidateCount: 3, passRate: 55 },
  { id: "stage_offer", name: "Offer", order: 6, candidateCount: 2, passRate: 42 },
  { id: "stage_hired", name: "Hired", order: 7, candidateCount: 1, passRate: 35 },
];

export const demoAnalytics: Analytics = {
  activeReqs: 3,
  totalCandidates: 13,
  avgTimeToFill: 38,
  offerAcceptanceRate: 67,
  assessmentPassRate: 71,
  interviewsThisWeek: 4,
  avgMatchScore: 85,
  pipelineValue: 2850000,
};
